package gopenai

// TokenUsage represents the usage of tokens for a GPT-3 completion request.
type TokenUsage struct {
	// PromptTokens is the number of tokens in the prompt text.
	PromptTokens int `json:"prompt_tokens"`
	// CompletionTokens is the number of tokens generated by the completion request.
	CompletionTokens int `json:"completion_tokens"`
	// TotalTokens is the sum of prompt tokens and completion tokens.
	TotalTokens int `json:"total_tokens"`
}
